site_info:
  base_title: "世界中で友達を作ろう！"
  base_description: "世界中で友達を作ろう！Huber.のガイドと素敵な旅を。"
  base_words: "Huber,ガイド,ツアー,ハーバー,旅,マッチング"
oauth:
  facebook:
    scope: "public_profile,email,user_friends"
    info_fields: "name, first_name, last_name, email"
profile:
  save:
    success: "プロフィールを更新しました。"
  send_message: 'ガイドへの相談には自己紹介の登録が必要です。自己紹介欄を入力してください。'
profile_images:
  save:
    success: "プロフィールを更新しました。"
profile_identities:
  save:
    success: "プロフィールを更新しました。"
profile_banks:
  save:
    success: "プロフィールを更新しました。"
    failure: "全ての項目を入力してください。"
categories:
  food: '食'
  alcohol: 'お酒'
  car: '車'
  cruising: '船旅'
  shopping: 'ショッピング'
  accommodation: '宿泊施設'
  business: 'ビジネス'
  sport: 'スポーツ'
languages:
  ja: '日本語'
  en: '英語'
  zh: '中国語'
listings:
  save:
    success: "ツアーページの登録に成功しました。次に、他の情報も入力してください。"
    failure: "ツアーページのタイトルと紹介文を入力してください。"
  set_lon_lat:
    error: "緯度経度情報の取得に失敗しました。以下より正確な場所を入力してください。"
  publish:
    success: "ツアーページを公開しました。"
    failure: "ツアーページの公開にはもう少し準備が必要です。"
  unpublish:
    success: "ツアーページを非公開にしました。"
    failure: "ツアーページの非公開に失敗しました。"
  delivery:
    ok: "出張可"
  error:
    invalid_listing_id: "該当するツアーが見つかりません。"
listing_images:
  save:
    success: "ツアーページの動画・画像の登録に成功しました。"
    failure: "動画・画像を選択してください。"
    failure_video: "動画のサイズが大きすぎます。<%= ENV["UPLOAD_VIDEO_LIMIT_SIZE"]%>MB以内の動画を登録してください。"
listing_details:
  save:
    success: "ツアー詳細情報の登録に成功しました。"
    failure: "集合場所の住所を設定してください。"
confections:
  save:
    success: "オプション1の情報を登録いたしました。"
    failure: "オプション1の情報の登録に失敗しました。"
tools:
  save:
    success: "オプション2の情報を登録しました。"
    failure: "オプション2情報の登録に失敗しました。"
dress_codes:
  save:
    success: "オプション3に関する情報を登録しました。"
    failure: "オプション3に関する情報の登録に失敗しました。"
  wafuku:
    only: "和服でお願いします。"
    not_only: "和服でなくて結構です。"
reservation:
  save:
    success: "ガイド内容を更新しました。"
    failure:
      no_date: "ツアーおよび予約日付を入力してください。"
      paypal_access_failure: 'paypalとの連携に失敗しました。'
      paypal_payment_failure: 'paypal決済に失敗しました。'
      paypal_refund_failure: 'paypal決済の取り消しに失敗しました。'
      paypal_canceled: '決済がキャンセルされました。'
      not_authorized_yet: 'ゲストにガイド内容を送信するには、信頼情報の登録と管理者による承認が必要です。'
  update:
    success: "ガイド内容を更新しました。"
    failure: "ガイド内容の更新に失敗しました。"
    no_date: "予約日付を入力してください。"
  requirement:
    profile:
      not_yet: "プロフィールを完成させてください。"
    profile_image:
      not_yet: "プロフィール画像をアップロードしてください。"
  msg:
    contact: "についての相談です。"
    reserve: "予約リクエストをお送りしました。"
    request: "ガイド内容をお送りしました。"
    accepted: "ガイド内容を承認しました。"
    canceled: "ガイド内容をキャンセルしました。"
    refunded: "払い戻し処理を実行しました。"
  progress:
    select: "予約を承認しますか？"
    select_by_guest: "予約をキャンセルする場合は、選択してください。"
    requested: "requested"
    canceled: "canceled"
    holded: "holded"
    accepted: "accepted"
    rejected: "rejected"
    listing_closed: "listing_closed"
  progress_for_message_thread:
    requested: "ただいま承認依頼中です。"
    canceled: "残念です…キャンセルされました。"
    accepted: "おめでとう！ガイド決定です！"
    rejected: "取り消しされました。新しい内容を確認してください。"
message_thread:
  show:
    message_form:
      content:
        placeholder: "ここにメッセージをご記入ください。"
message:
  save:
    success: "送信完了しました。"
    failure: "送信できませんでした。"
  read:
    string: "既読"
  unread:
    string: "未読"
  modal:
    message_to_host:
      title:
        label: "ガイドに連絡をする"
      form:
        submit:
          label: "メッセージを送る"
        content:
          placeholder: "ここにメッセージを入力ください"
    message_to_guest_from_reservation_manager:
      title:
        label: "予約依頼に回答する"
      form:
        submit:
          label: "回答を送る"
        content:
          placeholder: "例）当日は公共交通機関でおこしください。よろしくお願いいたします。"
    message_to_host_from_reservation_manager:
      title:
        label: "ガイドに連絡をする"
      form:
        submit:
          label: "メッセージを送る"
        content:
          placeholder: "例）どうぞよろしくおねがいします。"
user:
  host:
    noname: "ガイド"
    noname2: '名無し'
    this: 'こちらのガイド'
  noname: '名無し'
  left: '退会済みユーザー'
image:
  noimage:
    url: 'no-image-1024x640.gif'
    caption: '画像が登録されていません。'
  noimage2:
    url: 'no-image-225x225.gif'
    caption: ''
page:
  home: 'ホーム'
  dashboard: 'ダッシュボード'
  host_reservation_manager: '依頼受付'
  guest_reservation_manager: '予約申込'
  listing_new: 'ガイドになる'
  listings: 'ツアーページ'
  messages: 'メッセージ'
  wishlists: 'お気に入り'
  profile: 'プロフィール'
  account: 'アカウント'
  guest_flow: 'サービスの流れ'
  search: '検索'
  signup: 'アカウント作成'
  login: 'ログイン'
  logout: 'ログアウト'
  help: 'ヘルプ'
  subnav:
    top: 'トップ'
    photos: '写真'
    details: 'このガイドについて'
    reviews: 'レビュー'
    host_profile: 'ガイド紹介'
    neighborhood: '対応エリア'
mailer:
  from:
    default: "default-from-email@example.com"
  new_message:
    subject:
      #arrived: "新しいメッセージが届きました！"
      arrived: "Receive new message!"
  new_reservation:
    subject:
      #arrived: "予約リクエストが届きました！"
      arrived: "Receive new request!"
  new_guide_detail:
    subject:
      #arrived: "ガイド内容が届きました！"
      arrived: "Receive guide information!"
  update_reservation:
    subject:
      #canceled: "予約がキャンセルされました。"
      canceled: "Reservation has been canceled."
      #holded: "予約が保留されました。"
      holded: "Reservation has been holded."
      #accepted: "予約が成立しました！"
      accepted: "Reservation has been accepted!"
      #rejected: "予約が不成立となりました。"
      rejected: "Reservation has been rejected."
  review_notification:
    #subject: "レビューの記入をしませんか？"
    subject: "Let's fill in the review!"
  review_reply_notification:
    #subject: "レビューへの返信を記入しましょう。"
    subject: "Let's reply to review!"
  review_accept_notification:
    subject: "You got a review!"
  week_before_notification:
    subject: "It is a week to the appointment day!"
  day_before_notification:
    subject: "Tomorrow is the appointment day!"
left_steps:
  listing_image: "listing_image"
  listing_detail: "listing_detail"
  confection: "confection"
  tool: "tool"
  dress_code: "dress_code"
regulate_user:
  reservation_id:
    failure: "このページにはアクセスできません。予約IDが不正です。"
  user_id:
    failure: "このページにはアクセスできません。IDが不正です。"
  entry:
    duplicated: "既に投稿済みです。"
  review_not_found: "このページにはアクセスできません。レビューが見つかりません。"
regulate_term:
  expired: "レビューの書き込み期間が経過しました。"
review:
  save:
    success: "レビューを投稿しました。ガイドの方からの返信をお待ちください。"
    failure: "レビューを投稿できませんでした。"
  expiration_date: 14
review_reply:
  save:
    success: "レビューへの返信をしました。レビューが公開されましたので、ご確認ください。"
    failure: "レビューへの返信ができませんでした。"
