site_info:
  base_title: "Make friends all over the world! "
  base_description: "世界中で友達を作ろう！Huber.のガイドと素敵な旅を。"
  base_words: "Huber,ガイド,ツアー,ハーバー,旅,マッチング"
oauth:
  facebook:
    scope: "public_profile,email,user_friends"
    info_fields: "name, first_name, last_name, email"
    image_size: 'large'
profile:
  save:
    success: "Profile updated successfully"
    failure: "電話番号を正しく登録してください"
  send_message: 'Complete your profile in order to contact TOMODACHI GUIDE'
  deleted_profile_id: "This account has been canceled"
profile_images:
  save:
    success: "Profile updated successfully"
  delete:
    success: "Successfully deleted your photo"
profile_identities:
  save:
    success: "Profile updated successfully"
profile_banks:
  save:
    success: "Profile updated successfully"
    failure: "Please fill in all sections"
  number_length: 7
profile_keywords:
  save:
    success: "Profile updated successfully"
    failure: "Please fill in all sections"
categories:
  food: 'Food'
  alcohol: 'Alcohol'
  car: 'Car'
  cruising: 'Travel/Ship'
  shopping: 'Shopping'
  accommodation: 'Accommodation'
  business: 'Business'
  sport: 'Sports'
languages:
  ja: 'Japanese'
  en: 'English'
  zh: 'Chinese'
  de: 'German'
  fr: 'French'
  es: 'Spanish'
listings:
  save:
    success: "Tour-page has been updated successfully. Continue with the following steps to complete your tour-page"
    failure: "Enter a title and summary for your tour"
  set_lon_lat:
    error: "We couldn't find your exact address. Set an exact location below"
  publish:
    success: "You've updated your tour-page"
    failure: "More steps needed to finish your tour-page"
  unpublish:
    success: "Tour page hidden"
    failure: "Failed to set your tour page to hidden"
  destroy:
    success: "Listing was seccessfully deleted"
  copy:
    success: "Tour-page has been updated successfully. Continue with the following steps to complete your tour-page"
    failure: "Copying a tour failed"
  delivery:
    ok: "出張可"
  error:
    invalid_listing_id: "We couldn't find any results that matched your criteria"
    deleted_listing_id: "This tour has been deleted"
    closed: "This tour has been closed"
listing_images:
  save:
    success: "Successfully uploaded your photo/video"
    failure: "Add photos or videos"
    failure_video: "File size is too big. Please ensure file size is less than <%= ENV["UPLOAD_VIDEO_LIMIT_SIZE"]%>MB"
  delete:
    success: "Successfully deleted your photo/video"
listing_details:
  save:
    success: "Congratulations! You have successfully registered your tour"
    failure: "Choose a meeting place"
confections:
  save:
    success: "オプション1の情報を登録いたしました。"
    failure: "オプション1の情報の登録に失敗しました。"
tools:
  save:
    success: "オプション2の情報を登録しました。"
    failure: "オプション2情報の登録に失敗しました。"
dress_codes:
  save:
    success: "オプション3に関する情報を登録しました。"
    failure: "オプション3に関する情報の登録に失敗しました。"
  wafuku:
    only: "和服でお願いします。"
    not_only: "和服でなくて結構です。"
reservation:
  save:
    success: "Your tour plan has been uploaded successfully"
    failure:
      no_date: "Enter the dates available for this tour"
      paypal_access_failure: 'Connecting your account with Paypal failed'
      paypal_payment_failure: 'Authorization failed'
      paypal_refund_failure: 'Failed to withdraw authorization'
      paypal_canceled: 'Authorization cancelled'
      not_authorized_yet: 'We need to do a virtual ID check in order to send your tour plan to guests'
      invalid_campaign_code: 'Your campaign code is invalid'
      used_campaign_code: 'You have already used the campaign code'
  update:
    success: "Your tour plan has been uploaded successfully"
    cancel_success: 'キャンセルが完了しました。ガイドにもキャンセルの連絡が届けられていますので、まだ今回のキャンセルについて何も伝えていない時はメッセージを送るようにしましょう。'
    failure: "Updating your tour plan failed"
    no_date: "Choose when to book this tour"
  requirement:
    profile:
      not_yet: "Complete your profile"
    profile_image:
      not_yet: "Add a profile picture to your listing"
  msg:
    contact: "についての相談です。"
    reserve: "予約リクエストをお送りしました。"
    request: "ガイド内容をお送りしました。"
    accepted: "ガイド内容を承認しました。"
    canceled: "ガイド内容をキャンセルしました。"
    refunded: "払い戻し処理を実行しました。"
    reserve_en: "I sent you reservation request"
    request_en: "I sent you a tour plan"
    accepted_en: "I approved your tour plan"
    canceled_en: "I cancelled your tour plan"
    refunded_en: "Your refund has been authorized"
  progress:
    select: "予約を承認しますか？"
    select_by_guest: "予約をキャンセルする場合は、選択してください。"
    requested: "requested"
    canceled: "canceled"
    holded: "holded"
    accepted: "accepted"
    rejected: "rejected"
    listing_closed: "listing_closed"
    canceled_after_accepted: "canceled_after_accepted"
  progress_for_message_thread:
    requested: "Sending your tour plan..."
    canceled: "Sorry, Your request(Booking your tour) has been cancelled"
    accepted: "Congratulations! You have a booking!"
    rejected: "Tour plan was deleted, please confirm new information"
payment:
  refunds:
    policy: '8日以上前のキャンセル  ：エスクロー分の全額返金、1日〜7日前のキャンセル：エスクロー分の50％返金、24時間以内のキャンセル：返金なし'
    before_weeks_rate: 100
    before_days_rate: 50
message_thread:
  show:
    message_form:
      content:
        placeholder: "Write a message"
message:
  save:
    success: "Your message has been sent"
    failure: "message delivery failed"
    toobig: "Attached file is too big"
    notavailable: "This file is not available"
  read:
    string: "Read"
  unread:
    string: "Unread"
  modal:
    message_to_host:
      title:
        label: "ガイドに連絡をする"
      form:
        submit:
          label: "Send a message"
        content:
          placeholder: "Write a message"
    message_to_guest_from_reservation_manager:
      title:
        label: "予約依頼に回答する"
      form:
        submit:
          label: "回答を送る"
        content:
          placeholder: "例）当日は公共交通機関でおこしください。よろしくお願いいたします。"
    message_to_host_from_reservation_manager:
      title:
        label: "ガイドに連絡をする"
      form:
        submit:
          label: "Send a message"
        content:
          placeholder: "例）どうぞよろしくおねがいします。"
user:
  host:
    noname: "Guide"
    noname2: '名無し'
    this: 'こちらのガイド'
  noname: '名無し'
  left: '退会済みユーザー'
  destroy:
    success: '退会が完了しました。Huber.をご利用頂き誠にありがとうございました。'
image:
  noimage:
    url: 'no-image-1024x640.gif'
    caption: '画像が登録されていません。'
  noimage2:
    url: 'no-image-225x225.gif'
    caption: ''
page:
  home: 'Home'
  dashboard: 'Dashboard'
  host_reservation_manager: 'Your Bookings'
  guest_reservation_manager: 'Your Trips'
  listing_new: 'Become a guide'
  listings: 'Tour Page'
  messages: 'Message'
  wishlists: 'Favorite'
  profile: 'Profile'
  account: 'Account'
  favorites: 'Favorites'
  guest_flow: 'How It Works'
  search: 'Search'
  signup: 'Sign up'
  login: 'Log In'
  logout: 'Log Out'
  help: 'Help'
  subnav:
    top: 'Top'
    photos: '写真'
    details: 'このガイドについて'
    reviews: 'Review'
    host_profile: 'ガイド紹介'
    neighborhood: '対応エリア'
pre_mail:
  save:
    success: 'ガイド申請を受け付けました。'
    failure: 'ガイド申請に失敗しました。'
mailer:
  from:
    default: '"Huber." <noreply@huber-japan.com>'
    support: '"Huber." <support@m.huber.co.jp>'
  new_message:
    subject:
      #arrived: "新しいメッセージが届きました！"
      arrived: "You have a new message from"
  new_message_to_admin:
    subject:
      arrived: "新しいメッセージが作成されました"
  new_reservation:
    subject:
      #arrived: "予約リクエストが届きました！"
      arrived: "You have a reservation request from "
  new_reservation_to_admin:
    subject:
      arrived: "新しい予約リクエストが作成されました"
  new_guide_detail:
    subject:
      #arrived: "ガイド内容が届きました！"
      arrived: "Reservation status updated"
  update_reservation:
    subject:
      #canceled: "予約がキャンセルされました。"
      canceled: "Reservation has been canceled."
      #holded: "予約が保留されました。"
      holded: "Reservation has been holded."
      #accepted: "予約が成立しました！"
      accepted: "Reservation has been accepted!"
      #rejected: "予約が不成立となりました。"
      rejected: "Reservation has been rejected."
  review_notification:
    #subject: "レビューの記入をしませんか？"
    subject: "Please write a review for "
  review_reply_notification:
    #subject: "レビューへの返信を記入しましょう。"
    subject: "Please write a review for "
  review_accept_notification:
    subject: "You got a review!"
  week_before_notification:
    subject: "It is a week to the appointment day!"
  day_before_notification:
    subject: "Tomorrow is the appointment day!"
  send_cancel_mail_to_owner:
    subject: "ゲストが予約をキャンセルしました。"
  pre_mail:
    subject: "ガイド申請が届きました。"
  pre_mail_to_user:
    subject: "Huber.ガイド希望の確認メール"
  reply_mail_to_admin:
    subject: "ゲストへの返信がまだ行われていません"
left_steps:
  listing_image: "listing_image"
  listing_detail: "listing_detail"
  confection: "confection"
  tool: "tool"
  dress_code: "dress_code"
regulate_user:
  reservation_id:
    failure: "This page is unavailable, the reservation ID is incorrect"
  user_id:
    failure: "This page is unavailable, the ID is incorrect"
  entry:
    duplicated: "Your review has already been posted"
  review_not_found: "Page not found. No reviews yet"
regulate_term:
  expired: "You've missed the deadline for reviewing this tour"
review:
  save:
    success: "Your review has been posted succesfully. Please wait for a reply from your TOMODACHI GUIDE"
    failure: "Failed to post review"
  expiration_date: 14
review_reply:
  save:
    success: "Your review has been sent successfully. This review will be seen on your public page."
    failure: "Failed to reply to review"
